### ISSUE TITLE
Define SL_USER and SL_PASS

### ISSUE THREAD

**Issue by brommet87** [joheli/slabfr#2]
Hello, 

How can the variable SL_USER and SL_PASS been set? 

I can not find them in the .bat-file. 

Thanks in advance

**Comment by joheli** [comment]
Hi there,

both SL_USER and SL_PASS are environmental variables.

The process of setting environmental variables depends on your OS. Please refer to guides for [Windows](https://docs.oracle.com/en/database/oracle/machine-learning/oml4r/1.5.1/oread/creating-and-modifying-environment-variables-on-windows.html#GUID-DD6F9982-60D5-48F6-8270-A27EC53807D0), [Linux](https://www.serverlab.ca/tutorials/linux/administration-linux/how-to-set-environment-variables-in-linux/), or [MacOS](https://apple.stackexchange.com/questions/106778/how-do-i-set-environment-variables-on-os-x).

Kind regards

Johannes

**Comment by brommet87** [comment]
Thank you very much :-) 

I got it. 

Have a nice Weekend! 

regards, 

Christoph
